const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");

/**
 * Blockchain Service
 * -------------------
 * Provides functions to interact with the CredentialStorage smart contract
 * using ethers.js v6. Handles:
 *   - Connecting to the blockchain (local Hardhat or Sepolia)
 *   - Issuing credentials on-chain
 *   - Verifying credentials on-chain
 *   - Revoking credentials on-chain
 *   - Fetching student credentials from the blockchain
 */

// ========================
// Configuration
// ========================

// Load environment variables
const RPC_URL = process.env.BLOCKCHAIN_RPC_URL || "http://127.0.0.1:8545";
const PRIVATE_KEY = process.env.PRIVATE_KEY || "";

// Contract address — loaded from deployment config or .env
let CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS || "";

// Contract ABI — loaded from Hardhat compilation artifacts
let CONTRACT_ABI = [];

/**
 * Initialize the blockchain service by loading ABI and contract address.
 * This should be called once when the server starts.
 */
function initialize() {
  try {
    // Try to load deployment info (generated by deploy.js)
    const deploymentPath = path.join(__dirname, "../../config/deployment.json");
    if (fs.existsSync(deploymentPath)) {
      const deployment = JSON.parse(fs.readFileSync(deploymentPath, "utf8"));
      if (!CONTRACT_ADDRESS) {
        CONTRACT_ADDRESS = deployment.contractAddress;
      }
      console.log("📋 Contract address loaded from deployment config:", CONTRACT_ADDRESS);
    }

    // Try to load ABI from saved config (generated by deploy.js)
    const abiConfigPath = path.join(__dirname, "../../config/CredentialStorageABI.json");
    if (fs.existsSync(abiConfigPath)) {
      CONTRACT_ABI = JSON.parse(fs.readFileSync(abiConfigPath, "utf8"));
      console.log("📋 Contract ABI loaded from config");
      return;
    }

    // Fallback: load ABI from Hardhat artifacts
    const artifactPath = path.join(
      __dirname,
      "../../artifacts/contracts/CredentialStorage.sol/CredentialStorage.json"
    );
    if (fs.existsSync(artifactPath)) {
      const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
      CONTRACT_ABI = artifact.abi;
      console.log("📋 Contract ABI loaded from Hardhat artifacts");
    } else {
      console.warn("⚠️  No contract ABI found. Run 'npx hardhat compile' first.");
    }
  } catch (error) {
    console.error("❌ Error initializing blockchain service:", error.message);
  }
}

// ========================
// Provider & Signer Setup
// ========================

/**
 * Get an ethers.js provider connected to the configured RPC URL.
 */
function getProvider() {
  return new ethers.JsonRpcProvider(RPC_URL);
}

/**
 * Get an ethers.js wallet (signer) for sending transactions.
 * Uses the private key from environment variables.
 */
function getSigner() {
  const provider = getProvider();

  if (!PRIVATE_KEY) {
    throw new Error("PRIVATE_KEY not set in environment variables");
  }

  return new ethers.Wallet(PRIVATE_KEY, provider);
}

/**
 * Get a contract instance for reading (no signer needed).
 */
function getReadContract() {
  if (!CONTRACT_ADDRESS || CONTRACT_ABI.length === 0) {
    throw new Error(
      "Contract not configured. Deploy the contract first and ensure ABI is available."
    );
  }
  const provider = getProvider();
  return new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, provider);
}

/**
 * Get a contract instance for writing (signer needed).
 */
function getWriteContract() {
  if (!CONTRACT_ADDRESS || CONTRACT_ABI.length === 0) {
    throw new Error(
      "Contract not configured. Deploy the contract first and ensure ABI is available."
    );
  }
  const signer = getSigner();
  return new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, signer);
}

// ========================
// Contract Interaction Functions
// ========================

/**
 * Issue a credential on the blockchain.
 * @param {string} studentAddress - The student's Ethereum address
 * @param {string} credentialHash - The SHA-256 hash of the credential (hex string)
 * @returns {object} Transaction receipt with hash and block info
 */
async function issueCredentialOnChain(studentAddress, credentialHash) {
  try {
    const contract = getWriteContract();

    // Convert the hex hash string to bytes32 format
    // If the hash doesn't start with 0x, add it
    const hashBytes32 = credentialHash.startsWith("0x")
      ? credentialHash
      : "0x" + credentialHash;

    console.log(`🔗 Issuing credential on-chain...`);
    console.log(`   Student: ${studentAddress}`);
    console.log(`   Hash: ${hashBytes32}`);

    // Call the smart contract's issueCredential function
    const tx = await contract.issueCredential(studentAddress, hashBytes32);

    // Wait for the transaction to be mined
    console.log(`⏳ Transaction sent: ${tx.hash}`);
    const receipt = await tx.wait();

    console.log(`✅ Credential issued on-chain! Block: ${receipt.blockNumber}`);

    return {
      success: true,
      txHash: receipt.hash,
      blockNumber: receipt.blockNumber,
    };
  } catch (error) {
    console.error("❌ Blockchain issuing error:", error.message);
    throw new Error(`Failed to issue credential on blockchain: ${error.message}`);
  }
}

/**
 * Verify a credential on the blockchain.
 * @param {string} credentialHash - The SHA-256 hash to verify
 * @returns {object} Credential validity info (isValid, issuer, student, timestamp)
 */
async function verifyCredentialOnChain(credentialHash) {
  try {
    const contract = getReadContract();

    // Convert hash to bytes32 format
    const hashBytes32 = credentialHash.startsWith("0x")
      ? credentialHash
      : "0x" + credentialHash;

    console.log(`🔍 Verifying credential on-chain: ${hashBytes32}`);

    // Call the smart contract's verifyCredential function (view — no gas cost)
    const result = await contract.verifyCredential(hashBytes32);

    // Destructure the returned tuple
    const [isValid, issuer, student, timestamp] = result;

    // Check if the credential exists (issuer will be zero address if not)
    const exists = issuer !== ethers.ZeroAddress;

    return {
      exists,
      isValid,
      issuer,
      student,
      timestamp: exists ? Number(timestamp) : null,
      issuedAt: exists
        ? new Date(Number(timestamp) * 1000).toISOString()
        : null,
    };
  } catch (error) {
    console.error("❌ Blockchain verification error:", error.message);
    throw new Error(`Failed to verify credential on blockchain: ${error.message}`);
  }
}

/**
 * Revoke a credential on the blockchain.
 * @param {string} credentialHash - The SHA-256 hash of the credential to revoke
 * @returns {object} Transaction receipt
 */
async function revokeCredentialOnChain(credentialHash) {
  try {
    const contract = getWriteContract();

    const hashBytes32 = credentialHash.startsWith("0x")
      ? credentialHash
      : "0x" + credentialHash;

    console.log(`🚫 Revoking credential on-chain: ${hashBytes32}`);

    const tx = await contract.revokeCredential(hashBytes32);
    const receipt = await tx.wait();

    console.log(`✅ Credential revoked! Block: ${receipt.blockNumber}`);

    return {
      success: true,
      txHash: receipt.hash,
      blockNumber: receipt.blockNumber,
    };
  } catch (error) {
    console.error("❌ Blockchain revocation error:", error.message);
    throw new Error(`Failed to revoke credential on blockchain: ${error.message}`);
  }
}

/**
 * Get all credential hashes for a student from the blockchain.
 * @param {string} studentAddress - The student's Ethereum address
 * @returns {string[]} Array of credential hashes
 */
async function getStudentCredentialsOnChain(studentAddress) {
  try {
    const contract = getReadContract();

    console.log(`📚 Fetching credentials for student: ${studentAddress}`);

    const hashes = await contract.getStudentCredentials(studentAddress);

    // Convert bytes32 array to hex strings
    return hashes.map((hash) => hash);
  } catch (error) {
    console.error("❌ Blockchain fetch error:", error.message);
    throw new Error(`Failed to fetch student credentials from blockchain: ${error.message}`);
  }
}

// ========================
// Exports
// ========================

module.exports = {
  initialize,
  issueCredentialOnChain,
  verifyCredentialOnChain,
  revokeCredentialOnChain,
  getStudentCredentialsOnChain,
};
